# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

admin = User.create(email: 'admin@email.com', password:'123', role: 1)

admin.articles.create(title: 'test 1', body: 'Doggo ipsum such treat woofer heckin ruff, yapper smol. Most angery pupper I have ever seen bork clouds very jealous pupper heck borkf, aqua doggo you are doing me a frighten shibe tungg heckin good boys, bork length boy borking doggo such treat. Pats long doggo boofers very taste wow borking doggo very hand that feed shibe shooberino, much ruin diet smol shoob very hand that feed shibe bork. Wow such tempt long doggo mlem extremely cuuuuuute very taste wow smol borking doggo with a long snoot for pats, boofers dat tungg tho shoob.

Aqua doggo corgo wow very biscit puggorino, big ol pupper porgo. Super chub most angery pupper I have ever seen smol much ruin diet tungg big ol, wrinkler shoob long bois shoob. Lotsa pats noodle horse long bois aqua doggo, many pats waggy wags long water shoob, lotsa pats bork. You are doin me a concern floofs heckin bork heckin borkdrive heckin good boys, blop mlem puggo bork super chub. Shibe pats porgo extremely cuuuuuute smol heckin angery woofer, floofs shibe doggo. Shibe fat boi fluffer long bois, waggy wags. Shoob the neighborhood pupper I am bekom fat corgo, pupperino waggy wags, he made many woofs long water shoob. Very hand that feed shibe super chub extremely cuuuuuute noodle horse borkdrive pupper much ruin diet waggy wags, yapper waggy wags big ol doggorino wow such tempt wow very biscit. heckin good boys. Aqua doggo blop very good spot porgo long woofer ur givin me a spook you are doin me a concern, aqua doggo bork heckin angery woofer doggorino.

Smol borking doggo with a long snoot for pats noodle horse adorable doggo sub woofer, bork. Big ol pupper dat tungg tho fat boi you are doin me a concern vvv, adorable doggo boofers. Mlem long water shoob pupperino, borkdrive. Long woofer boof h*ck doge, heckin. Dat tungg tho long water shoob very taste wow very jealous pupper big ol long woofer, puggo such treat very jealous pupper long doggo. You are doin me a concern smol borking doggo with a long snoot for pats ruff, many pats. Very jealous pupper super chub extremely cuuuuuute many pats porgo, yapper most angery pupper I have ever seen.  Fluffer sub woofer fat boi thicc very jealous pupper he made many woofs waggy wags puggorino bork most angery pupper I have ever seen, big ol pupper sub woofer doge h*ck I am bekom fat maximum borkdrive super chub.')

admin.articles.create(title: 'test 2', body: 'Doggo ipsum such treat woofer heckin ruff, yapper smol. Most angery pupper I have ever seen bork clouds very jealous pupper heck borkf, aqua doggo you are doing me a frighten shibe tungg heckin good boys, bork length boy borking doggo such treat. Pats long doggo boofers very taste wow borking doggo very hand that feed shibe shooberino, much ruin diet smol shoob very hand that feed shibe bork. Wow such tempt long doggo mlem extremely cuuuuuute very taste wow smol borking doggo with a long snoot for pats, boofers dat tungg tho shoob.

Aqua doggo corgo wow very biscit puggorino, big ol pupper porgo. Super chub most angery pupper I have ever seen smol much ruin diet tungg big ol, wrinkler shoob long bois shoob. Lotsa pats noodle horse long bois aqua doggo, many pats waggy wags long water shoob, lotsa pats bork. You are doin me a concern floofs heckin bork heckin borkdrive heckin good boys, blop mlem puggo bork super chub. Shibe pats porgo extremely cuuuuuute smol heckin angery woofer, floofs shibe doggo. Shibe fat boi fluffer long bois, waggy wags. Shoob the neighborhood pupper I am bekom fat corgo, pupperino waggy wags, he made many woofs long water shoob. Very hand that feed shibe super chub extremely cuuuuuute noodle horse borkdrive pupper much ruin diet waggy wags, yapper waggy wags big ol doggorino wow such tempt wow very biscit. heckin good boys. Aqua doggo blop very good spot porgo long woofer ur givin me a spook you are doin me a concern, aqua doggo bork heckin angery woofer doggorino.

Smol borking doggo with a long snoot for pats noodle horse adorable doggo sub woofer, bork. Big ol pupper dat tungg tho fat boi you are doin me a concern vvv, adorable doggo boofers. Mlem long water shoob pupperino, borkdrive. Long woofer boof h*ck doge, heckin. Dat tungg tho long water shoob very taste wow very jealous pupper big ol long woofer, puggo such treat very jealous pupper long doggo. You are doin me a concern smol borking doggo with a long snoot for pats ruff, many pats. Very jealous pupper super chub extremely cuuuuuute many pats porgo, yapper most angery pupper I have ever seen.  Fluffer sub woofer fat boi thicc very jealous pupper he made many woofs waggy wags puggorino bork most angery pupper I have ever seen, big ol pupper sub woofer doge h*ck I am bekom fat maximum borkdrive super chub.')

admin.articles.create(title: 'test 3', body: 'Doggo ipsum such treat woofer heckin ruff, yapper smol. Most angery pupper I have ever seen bork clouds very jealous pupper heck borkf, aqua doggo you are doing me a frighten shibe tungg heckin good boys, bork length boy borking doggo such treat. Pats long doggo boofers very taste wow borking doggo very hand that feed shibe shooberino, much ruin diet smol shoob very hand that feed shibe bork. Wow such tempt long doggo mlem extremely cuuuuuute very taste wow smol borking doggo with a long snoot for pats, boofers dat tungg tho shoob.

Aqua doggo corgo wow very biscit puggorino, big ol pupper porgo. Super chub most angery pupper I have ever seen smol much ruin diet tungg big ol, wrinkler shoob long bois shoob. Lotsa pats noodle horse long bois aqua doggo, many pats waggy wags long water shoob, lotsa pats bork. You are doin me a concern floofs heckin bork heckin borkdrive heckin good boys, blop mlem puggo bork super chub. Shibe pats porgo extremely cuuuuuute smol heckin angery woofer, floofs shibe doggo. Shibe fat boi fluffer long bois, waggy wags. Shoob the neighborhood pupper I am bekom fat corgo, pupperino waggy wags, he made many woofs long water shoob. Very hand that feed shibe super chub extremely cuuuuuute noodle horse borkdrive pupper much ruin diet waggy wags, yapper waggy wags big ol doggorino wow such tempt wow very biscit. heckin good boys. Aqua doggo blop very good spot porgo long woofer ur givin me a spook you are doin me a concern, aqua doggo bork heckin angery woofer doggorino.

Smol borking doggo with a long snoot for pats noodle horse adorable doggo sub woofer, bork. Big ol pupper dat tungg tho fat boi you are doin me a concern vvv, adorable doggo boofers. Mlem long water shoob pupperino, borkdrive. Long woofer boof h*ck doge, heckin. Dat tungg tho long water shoob very taste wow very jealous pupper big ol long woofer, puggo such treat very jealous pupper long doggo. You are doin me a concern smol borking doggo with a long snoot for pats ruff, many pats. Very jealous pupper super chub extremely cuuuuuute many pats porgo, yapper most angery pupper I have ever seen.  Fluffer sub woofer fat boi thicc very jealous pupper he made many woofs waggy wags puggorino bork most angery pupper I have ever seen, big ol pupper sub woofer doge h*ck I am bekom fat maximum borkdrive super chub.')
